# Generated by Django 2.1.7 on 2019-04-04 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_form_level_permission',
            name='form_type',
            field=models.CharField(blank=True, choices=[('LIST', 'LIST'), ('REPORT', 'REPORT'), ('DETAIL', 'DETAIL'), ('MIXED', 'MIXED')], max_length=6, null=True),
        ),
    ]
