# Generated by Django 2.1.7 on 2019-04-04 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0002_user_form_level_permission_form_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='app_form',
            name='form_type',
            field=models.CharField(blank=True, choices=[('LIST', 'LIST'), ('REPORT', 'REPORT'), ('DETAIL', 'DETAIL'), ('MIXED', 'MIXED')], max_length=6, null=True),
        ),
    ]
