# Generated by Django 2.1.7 on 2019-04-16 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0003_app_form_form_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_form_level_permission',
            name='full_privilege_on',
            field=models.BooleanField(default=False),
        ),
    ]
