# Generated by Django 2.1.7 on 2019-04-16 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0004_user_form_level_permission_full_privilege_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app_form',
            name='form_type',
            field=models.CharField(blank=True, choices=[('LIST', 'LIST'), ('REPORT', 'REPORT'), ('DETAIL', 'DETAIL'), ('MIXED', 'MIXED')], max_length=6),
        ),
    ]
