# Generated by Django 2.1.7 on 2019-03-23 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset_Type',
            fields=[
                ('asset_id', models.AutoField(primary_key=True, serialize=False)),
                ('asset_type', models.CharField(max_length=80, unique=True)),
            ],
            options={
                'verbose_name': 'Asset Type',
                'verbose_name_plural': 'Asset Types',
            },
        ),
        migrations.CreateModel(
            name='Association_Type',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Business_Bucket',
            fields=[
                ('bucket_id', models.AutoField(primary_key=True, serialize=False)),
                ('bucket_name', models.CharField(max_length=80, unique=True)),
            ],
            options={
                'verbose_name': 'Business Bucket',
                'verbose_name_plural': 'Business Buckets',
            },
        ),
        migrations.CreateModel(
            name='Contract_Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefix', models.CharField(blank=True, default=None, max_length=50, unique=True)),
                ('main_category', models.CharField(default=None, max_length=50)),
                ('sub_category', models.CharField(blank=True, default=None, max_length=50)),
            ],
            options={
                'verbose_name': 'Contract Type',
                'verbose_name_plural': 'Contract Type',
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('dept_id', models.AutoField(primary_key=True, serialize=False)),
                ('dept_name', models.CharField(max_length=80, unique=True)),
            ],
            options={
                'verbose_name': 'Department',
                'verbose_name_plural': 'Departments',
            },
        ),
        migrations.CreateModel(
            name='Genres_List',
            fields=[
                ('genre_id', models.AutoField(primary_key=True, serialize=False)),
                ('genre_name', models.CharField(max_length=60, unique=True)),
                ('added_on', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Genre List',
                'verbose_name_plural': 'Genres List',
            },
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('lang_id', models.AutoField(primary_key=True, serialize=False)),
                ('language_name', models.CharField(max_length=60, unique=True)),
            ],
            options={
                'verbose_name': 'Language',
                'verbose_name_plural': 'Languages',
            },
        ),
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('plat_id', models.AutoField(primary_key=True, serialize=False)),
                ('platform_name', models.CharField(max_length=70, unique=True)),
            ],
            options={
                'verbose_name': 'Platform',
                'verbose_name_plural': 'Platforms',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('tag_id', models.AutoField(primary_key=True, serialize=False)),
                ('tag_name', models.CharField(max_length=100, unique=True)),
            ],
        ),
    ]
