# Generated by Django 2.1.7 on 2019-04-09 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cfms', '0002_contract_contract_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contract',
            name='status',
        ),
        migrations.AlterField(
            model_name='contract',
            name='contract_status',
            field=models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive'), ('Draft', 'Draft')], default='Draft', max_length=15),
        ),
    ]
