# Generated by Django 2.1.7 on 2019-04-16 07:25

import cfms.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cfms', '0003_auto_20190409_1156'),
    ]

    operations = [
        migrations.CreateModel(
            name='IPRight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default=cfms.models.IPRight.get_autogenerated_code, editable=False, max_length=20)),
                ('entity', models.CharField(max_length=100)),
                ('right_type', models.CharField(choices=[('Both', 'Exclusive & Non Exclusive'), ('Excl', 'Exclusive'), ('NExc', 'Non Exclusive')], default='Both', max_length=30)),
                ('exclusivity', models.CharField(default='None', max_length=100)),
                ('inclusivity', models.CharField(default='All', max_length=100)),
            ],
        ),
    ]
