# Generated by Django 2.1.7 on 2019-04-16 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cfms', '0004_ipright'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ipright',
            options={'verbose_name': 'IP Right'},
        ),
    ]
