# Generated by Django 2.1.7 on 2019-04-16 07:40

import cfms.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cfms', '0005_auto_20190416_0727'),
    ]

    operations = [
        migrations.CreateModel(
            name='IPRightGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default=cfms.models.IPRightGroup.get_autogenerated_code, editable=False, max_length=20)),
                ('ip_right', models.ManyToManyField(to='cfms.IPRight')),
            ],
            options={
                'verbose_name': 'IP Rights Group',
            },
        ),
    ]
