# Generated by Django 2.1.7 on 2019-04-16 10:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cfms', '0006_iprightgroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='rights_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contract_associated_ip_rights_group', to='cfms.IPRightGroup'),
        ),
    ]
