# Generated by Django 2.1.7 on 2019-04-16 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cfms', '0007_contract_rights_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contract',
            name='wom_affiliated',
        ),
    ]
