# Generated by Django 2.1.7 on 2019-03-23 10:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('property', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='property_ownership',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('channel_name_id_fk', models.ManyToManyField(to='property.channel')),
                ('cms_name_id_fk', models.ManyToManyField(to='property.cms')),
                ('facebook_page_id_fk', models.ManyToManyField(to='property.facebook')),
                ('instagram_account_name_id_fk', models.ManyToManyField(to='property.instagram')),
                ('twitter_account_name_id_fk', models.ManyToManyField(to='property.twitter')),
                ('user_id_fk', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Select User')),
            ],
            options={
                'verbose_name': 'Property_ownership',
                'verbose_name_plural': 'Property_ownership',
            },
        ),
    ]
