# Generated by Django 2.1.7 on 2019-04-16 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('raci', '0002_property_ownership_contract_id_fk'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property_ownership',
            name='contract_id_fk',
        ),
    ]
