# Generated by Django 2.1.7 on 2019-03-23 10:59

import dam.models
import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CloudFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default=dam.models.CloudFile.get_autogenerated_code, editable=False, max_length=8)),
                ('nas_path', models.CharField(blank=True, max_length=200)),
                ('remote_storage_label', models.CharField(blank=True, max_length=100)),
                ('remote_path', models.CharField(blank=True, max_length=200)),
                ('keywords', models.TextField(blank=True)),
                ('hex_digest', models.CharField(default='', max_length=40)),
                ('last_accessed_time', models.DateTimeField(null=True)),
                ('retrieval_frequency', models.IntegerField(blank=True, default=0)),
                ('is_readily_available', models.BooleanField(default=True)),
                ('added_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='DownloadLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default=dam.models.DownloadLog.get_autogenerated_code, editable=False, max_length=20)),
                ('activity_time', models.DateTimeField(default=datetime.datetime.now, editable=False)),
                ('status', models.BooleanField(default=False)),
                ('cfile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cfile_downloaded', to='dam.CloudFile')),
                ('downloaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cfile_downloaded_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('env_type', models.CharField(choices=[('LINUX', 'LINUX'), ('WINDOWS', 'WINDOWS'), ('APPLE', 'APPLE')], max_length=15)),
                ('identity', models.CharField(max_length=20, verbose_name='Machine Code')),
                ('pubic_key_path', models.CharField(blank=True, max_length=150, verbose_name='SSH Public Key')),
                ('latest_pulse_check', models.DateTimeField()),
                ('lan_ip', models.CharField(default='', max_length=40)),
                ('is_alive', models.BooleanField()),
                ('machine_status', models.CharField(choices=[('NC', 'NOT CONFIGURED'), ('OOS', 'OUT OF SERVICE'), ('CO', 'CONFIGURED OK')], max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='Nudge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default=dam.models.Nudge.get_autogenerated_code, editable=False, max_length=20)),
                ('nudged_on', models.DateTimeField(default=datetime.datetime.now, editable=False)),
                ('status', models.BooleanField(default=False)),
                ('cfile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nudged_for_file', to='dam.CloudFile')),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nudge_from_machine', to='dam.Machine')),
                ('nudged_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nudged_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default=dam.models.Request.get_autogenerated_code, editable=False, max_length=20)),
                ('tat_minutes', models.IntegerField(blank=True, default=0)),
                ('request_placed_on', models.DateTimeField(default=datetime.datetime.now, editable=False)),
                ('request_closed_on', models.DateTimeField()),
                ('status', models.BooleanField(default=False)),
                ('is_archieved', models.BooleanField(default=False)),
                ('cfile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='request_from_machine_for_cfile', to='dam.CloudFile')),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='request_from_machine', to='dam.Machine')),
                ('request_created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='request_created_by', to=settings.AUTH_USER_MODEL)),
                ('request_served_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='request_served_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cloud File Request',
                'verbose_name_plural': 'Cloud File Requests',
            },
        ),
        migrations.CreateModel(
            name='StorageDevice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default=dam.models.StorageDevice.get_autogenerated_code, editable=False, max_length=20)),
                ('local_name', models.CharField(max_length=50)),
                ('last_updated_on', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
        migrations.AddField(
            model_name='downloadlog',
            name='machine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='download_from_machine', to='dam.Machine'),
        ),
        migrations.AddField(
            model_name='cloudfile',
            name='storage_label',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dam.StorageDevice'),
        ),
    ]
