# Generated by Django 2.1.7 on 2019-03-23 10:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hcpc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=200)),
                ('volume', models.FloatField(blank=True, default=None, null=True)),
                ('keyword_difficulty', models.FloatField(blank=True, default=None, null=True)),
                ('cost_per_click', models.FloatField(blank=True, default=None, null=True)),
                ('competitive_density', models.FloatField(blank=True, default=None, null=True)),
                ('results', models.FloatField(blank=True, default=None, null=True)),
                ('serp_features', models.CharField(blank=True, max_length=200)),
                ('date', models.DateField(blank=True, default=datetime.date.today)),
            ],
            options={
                'verbose_name': 'High Performing Keyword',
                'verbose_name_plural': 'High Performing Keywords',
            },
        ),
        migrations.CreateModel(
            name='TrendingKeywords',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=200)),
                ('volume', models.FloatField(blank=True, default=None, null=True)),
                ('keyword_difficulty', models.FloatField(blank=True, default=None, null=True)),
                ('cost_per_click', models.FloatField(blank=True, default=None, null=True)),
                ('competitive_density', models.FloatField(blank=True, default=None, null=True)),
                ('results', models.FloatField(blank=True, default=None, null=True)),
                ('serp_features', models.CharField(blank=True, max_length=200)),
                ('date', models.DateField(blank=True, default=datetime.date.today)),
            ],
            options={
                'verbose_name': 'Trending Keyword',
                'verbose_name_plural': 'Trending Keywords',
            },
        ),
    ]
