# Generated by Django 2.1.7 on 2019-03-23 10:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('property', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ytm_upload_track',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('track', models.CharField(max_length=200, verbose_name='Video Title')),
                ('channel_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='property.channel', verbose_name='Select Channel')),
                ('uploader_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Upload Track',
                'verbose_name_plural': 'Upload Tracks',
            },
        ),
    ]
