# Generated by Django 2.1.7 on 2019-04-18 06:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0004_auto_20190418_0647'),
    ]

    operations = [
        migrations.AddField(
            model_name='facebook',
            name='created_on',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Date'),
            preserve_default=False,
        ),
    ]
