# Generated by Django 2.1.7 on 2019-04-18 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0005_facebook_created_on'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='youtube_videos',
            name='video_published_at',
        ),
    ]
