# Generated by Django 2.1.7 on 2019-04-18 06:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0006_remove_youtube_videos_video_published_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='youtube_videos',
            name='video_published_at',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='Video Published Time'),
        ),
    ]
