# Generated by Django 2.1.7 on 2019-04-18 07:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0007_youtube_videos_video_published_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='youtube_videos',
            name='video_published_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, verbose_name='Video Published Time'),
        ),
    ]
