# Generated by Django 2.1.7 on 2019-04-18 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0008_auto_20190418_0700'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='youtube_videos',
            name='video_published_at',
        ),
    ]
